FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV REFRESHED_AT=2024-08-12

LABEL io.k8s.description="Headless VNC with DeepFaceLive (crazidev fork), IceWM, noVNC" \
      io.k8s.display-name="DeepFaceLive headless VNC (IceWM)" \
      io.openshift.expose-services="6901:http,5901:xvnc,1234:udp-out,18766:udp-in,8890:srt,1935:rtmp,8554:rtsp,9090:http,10000:webrtc" \
      io.openshift.tags="vnc,deepfacelive,icewm,cuda" \
      io.openshift.non-scalable=true

### Connection ports for controlling the UI:
### VNC port:5901
### noVNC webport, connect via http://IP:6901/?password=vncpassword
### DeepFaceLive streaming: set DFL_* at runtime (RunPod). Typical: UDP 1234 out, 18766 in, 8890 SRT, 1935 RTMP, 8554 RTSP
###   TCP 9090  DFL_WEBRTC_PORT (WebRTC Signaling & WebApp)
###   UDP 10000 WebRTC Video Channel (Method A direct)
###   TCP 10000 WebRTC Video Channel Backup (Method A TCP)
ENV DISPLAY=:1 \
    VNC_PORT=5901 \
    NO_VNC_PORT=6901
EXPOSE $VNC_PORT $NO_VNC_PORT 8080/tcp 8585/tcp 1234/udp 18766/udp 8890/udp 1935/tcp 8554/tcp 9090/tcp 10000/tcp 10000/udp

### Envrionment config
ENV HOME=/workspace \
    TERM=xterm \
    STARTUPDIR=/dockerstartup \
    INST_SCRIPTS=/workspace/install \
    NO_VNC_HOME=/workspace/noVNC \
    DEBIAN_FRONTEND=noninteractive \
    VNC_COL_DEPTH=24 \
    VNC_PW=vncpassword \
    VNC_VIEW_ONLY=false \
    TZ=Asia/Seoul
WORKDIR $HOME

### Install necessary dependencies
RUN apt-get update && apt-get install -y \
    wget \
    git \
    build-essential \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    git \
    unzip \
    ffmpeg \
    jq \
    tzdata && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/*

### Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
bash miniconda.sh -b -p /opt/conda && \
rm miniconda.sh

### Add Conda to the PATH
ENV PATH=/opt/conda/bin:$PATH

### Add all install scripts for further steps
ADD ./src/common/install/ $INST_SCRIPTS/
ADD ./src/debian/install/ $INST_SCRIPTS/
RUN chmod 765 $INST_SCRIPTS/*

### Install some common tools
RUN $INST_SCRIPTS/tools.sh
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

### Install custom fonts
RUN $INST_SCRIPTS/install_custom_fonts.sh

### Install xvnc-server & noVNC - HTML5 based VNC viewer
RUN $INST_SCRIPTS/tigervnc.sh
RUN $INST_SCRIPTS/no_vnc_1.5.0.sh

### Install firefox and chrome browser
RUN $INST_SCRIPTS/firefox.sh

### Install IceWM UI
RUN $INST_SCRIPTS/icewm_ui.sh
ADD ./src/debian/icewm/ $HOME/

### PyQt6 / OpenCV runtime libs for DeepFaceLive
RUN $INST_SCRIPTS/deepfacelive_apt.sh

### configure startup
RUN $INST_SCRIPTS/libnss_wrapper.sh
ADD ./src/common/scripts $STARTUPDIR
RUN $INST_SCRIPTS/set_user_permission.sh $STARTUPDIR $HOME

### Create conda environment (accept Anaconda channel ToS for non-interactive builds)
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    conda create -n DeepFaceLive python=3.10.13 -y && conda clean --all -y

### Activate the environment
ENV CONDA_DEFAULT_ENV=DeepFaceLive
RUN echo "source activate $CONDA_DEFAULT_ENV" >> ~/.bashrc
ENV PATH=/opt/conda/envs/$CONDA_DEFAULT_ENV/bin:$PATH

ENV DFL_DEEPFACELIVE_HOME=/workspace/DeepFaceLive \
    QT_QPA_PLATFORM=xcb

WORKDIR /workspace
RUN git clone --depth 1 https://github.com/crazidev/DeepFaceLive.git DeepFaceLive
WORKDIR /workspace/DeepFaceLive

COPY ./src/deepfacelive/requirements-gpu.txt /tmp/requirements-gpu.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /tmp/requirements-gpu.txt

RUN mkdir -p data && cp -a build/animatables build/samples data/

### Install jupyterlab
RUN pip install jupyterlab

### Install filebrowser
RUN wget -O - https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash

### Reconfigure startup
COPY ./src/vnc_startup_jupyterlab_filebrowser.sh /dockerstartup/vnc_startup.sh
RUN chmod 765 /dockerstartup/vnc_startup.sh

ENV VNC_RESOLUTION=1280x1024

ENTRYPOINT ["/dockerstartup/vnc_startup.sh"]
CMD ["--wait"]
